### ISSUE TITLE
Style theme using a React-friendly library like @emotion or @styled-components

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/gatsby-starter-wordpress-graphql#10]
I'm not putting `className` on every HTML tag in this starter. That's _not_ the "react" way. I'm a big fan of how [Emotion](https://emotion.sh/docs/introduction), [Styled Components](https://www.styled-components.com/) and [Theme-UI](https://theme-ui.com/) handles CSS-in-JS styles.

**Comment by martinDolan** [comment]
Branch:
https://github.com/WebDevStudios/gatsby-starter-wordpress-graphql/tree/feature/%2310-style-library

I've added the Emotion plugin and dependencies. 

I've also created a quick demo page. It's not pretty but it puts a stake in the ground.
/emotion-demo-delete-me

<img width="778" alt="Screenshot 2019-08-31 16 47 50" src="https://user-images.githubusercontent.com/5550150/64069027-4d010900-cc0f-11e9-9d94-d3d4553659af.png">

**Comment by martinDolan** [comment]
Hey @gregrickaby,
 I'm wondering if you're thinking this is just a short task, as in just adding the Emotion library, or if you're thinking this is a larger task - perhaps something like recreating all of the base wd_s styles in emotion?

**Comment by gregrickaby** [comment]
@martinDolan I wouldn't mind doing basic styles like wd_s

**Comment by martinDolan** [comment]
@gregrickaby - I've made some progress on this issue in several ways since our last call. 

I have a WIP branch at: 
https://github.com/WebDevStudios/gatsby-starter-wordpress-graphql/tree/feature/working-with-typography-js

How can you help:
Check out this branch and take a look. Any feedback you have on the overall direction of this would be great. I didn't want to get TOO far into the weeds before sharing this, because this particular issue will have far-reaching implications for everyone. This is still pretty fresh, but the overall proof of concept is in place. The file structure is still in the works, as I have type related files in different places. Basically, it's Typography JS for the base styles, and Theme UI for styling components. Of course that includes Emotion. 

Do you like the overall direction this is taking? 

Would you do it differently?

1. I've added Theme UI and a demo of that (adds some very basic style tweaks as a proof of concept). 
-Those additions are visible on the homepage in this branch - notice the mint background color. 
-You can see where i'm importing the emotion object and using it in `src/pages/index.js`
- The theme object is defined in `src/gatsby-plugin-theme-ui/index.js`

2. Adds Typography JS as a way of managing the base styles. Also adds some base styles for body tags and breakpoints.
Those files can be found at:
`src/utils/typography.js`
`src/utils/test-breakpoints.js`

<img width="1599" alt="Screenshot 2019-09-09 14 59 28" src="https://user-images.githubusercontent.com/5550150/64559485-680d0080-d314-11e9-818c-c8431f99a7a0.png">
